blank_issues_enabled: true
contact_links:
  - name: 💬 I have a question or need support
    url: https://github.com/sourcectl/feedback/discussions
    about: The perfect place to raise questions, start discussions around a sourcectl topic with others, and ask for support.